Repository SnowWhiteEPFL/edweiss, pull requests merged in 2024-11, with the labels that each got.

#19 ✨ feat: Code Cleanup and Addition of Notifications Page
  edweiss-app/__test__/components/AssignmentDisplay.test.tsx
  edweiss-app/__test__/home_page/Day.test.tsx
  edweiss-app/__test__/home_page/formatTime.test.tsx
  edweiss-app/__test__/home_page/getCurrentDay.test.tsx
  edweiss-app/__test__/home_page/getCurrentTimeInMinutes.test.tsx
  edweiss-app/__test__/utils/utilsFunctions.test.ts
  edweiss-app/app/(app)/(tabs)/_layout.tsx
  edweiss-app/app/(app)/(tabs)/notifications.tsx
  edweiss-app/app/(app)/courses/[id]/archive.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/app/(app)/startCourseScreen/index.tsx
  edweiss-app/assets/images/no-notification.png
  edweiss-app/components/calendar/CalendarDisplay.tsx
  edweiss-app/components/core/TText.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/components/notifs/NotifDisplay.tsx
  edweiss-app/config/i18config.ts
  edweiss-app/constants/Colors.ts
  edweiss-app/constants/Sizes.ts
  edweiss-app/constants/Time.ts
  edweiss-app/locales/en/notifications.json
  edweiss-app/model/notifs.ts
  edweiss-app/model/school/courses.ts
  edweiss-app/utils/color.ts
  edweiss-firebase/functions/src/functions/notifs/deleteNotif.ts
  edweiss-firebase/functions/src/functions/notifs/markAsRead.ts
  edweiss-firebase/functions/src/functions/notifs/markAsUnread.ts
  edweiss-firebase/functions/src/functions/notifs/pushNotif.ts
  edweiss-firebase/functions/src/model/notifs.ts
  edweiss-firebase/functions/src/model/school/courses.ts
Labels: !!!priority for merging

#13 Todolist refractoring and test suites support
  .github/workflows/test.yml
  .gitignore
  edweiss-app/__test__/app/(app)/todo/create.test.tsx
  edweiss-app/__test__/app/(app)/todo/edit.test.tsx
  edweiss-app/__test__/app/(app)/todo/index.test.tsx
  edweiss-app/__test__/components/todo/abstractTodoEditor.test.tsx
  edweiss-app/__test__/components/todo/modal.test.tsx
  edweiss-app/__test__/components/todo/todoDisplay.test.tsx
  edweiss-app/__test__/utils/time.test.ts
  edweiss-app/__test__/utils/todo/utilsFunctions.test.tsx
  edweiss-app/app/(app)/lectures/remotecontrol/index.tsx
  edweiss-app/app/(app)/lectures/slides/index.tsx
  edweiss-app/app/(app)/test_showTime/index.tsx
  edweiss-app/app/(app)/todo/create.tsx
  edweiss-app/app/(app)/todo/edit.tsx
  edweiss-app/app/(app)/todo/index.tsx
  edweiss-app/components/core/header/HeaderButton.tsx
  edweiss-app/components/todo/abstractTodoEditor.tsx
  edweiss-app/components/todo/modal.tsx
  edweiss-app/components/todo/todoDisplay.tsx
  edweiss-app/model/school/schedule.ts
  edweiss-app/model/time.ts
  edweiss-app/model/todo.ts
  edweiss-app/package-lock.json
  edweiss-app/package.json
  edweiss-app/utils/time.ts
  edweiss-app/utils/todo/utilsFunctions.tsx
  edweiss-firebase/functions/src/functions/todolist/createTodo.ts
  edweiss-firebase/functions/src/functions/todolist/deleteTodo.ts
  edweiss-firebase/functions/src/functions/todolist/updateTodo.ts
  edweiss-firebase/functions/src/model/school/schedule.ts
  edweiss-firebase/functions/src/model/todo.ts
  edweiss-web/src/model/school/courses.ts
  edweiss-web/src/model/school/schedule.ts
  edweiss-web/src/model/time.ts
  edweiss-web/src/model/todo.ts
  model/src/todo.ts
Labels: test

#30 Fix the duplicate todo problem.
  .github/workflows/test.yml
  edweiss-app/__test__/components/todo/abstractTodoEditor.test.tsx
  edweiss-app/__test__/utils/time.test.ts
  edweiss-app/app/(app)/todo/index.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/components/todo/abstractTodoEditor.tsx
  edweiss-app/locales/en/todo.json
  edweiss-app/model/todo.ts
  edweiss-app/utils/time.ts
  edweiss-firebase/functions/src/functions/todolist/createTodo.ts
  edweiss-firebase/functions/src/functions/todolist/updateTodo.ts
  edweiss-firebase/functions/src/model/todo.ts
  edweiss-web/src/model/todo.ts
  model/src/todo.ts
Labels: bug

#37 Fix Element Type Error and Refactor Test Mocks for RemoteControlScreen tests
  edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx
  edweiss-app/app/(app)/lectures/remotecontrol/index.tsx
Labels: bug

#38 Tests/course pages tests
  edweiss-app/__test__/components/AssignmentDisplay.test.tsx
  edweiss-app/__test__/components/courses/AssignmentDisplay.test.tsx
  edweiss-app/__test__/courses/ArchivePage.test.tsx
  edweiss-app/__test__/courses/CoursePage.test.tsx
  edweiss-app/__test__/utils/courses/saveToDo.test.tsx
  edweiss-app/__test__/utils/time.test.ts
  edweiss-app/app/(app)/courses/[id]/archive.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/components/notifs/NotifDisplay.tsx
  edweiss-app/package-lock.json
  edweiss-app/utils/courses/saveToDo.tsx
  edweiss-app/utils/time.ts
  package-lock.json
Labels: test

#34 Providing test suites for the ShowTime Remote Control
  .github/workflows/test.yml
  edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/abstractRmtCtl.test.tsx
  edweiss-app/__test__/utils/lectures/remotecontrol/utilsFunctions.test.ts
  edweiss-app/app/(app)/lectures/remotecontrol/index.tsx
  edweiss-app/components/lectures/remotecontrol/abstractRmtCtl.tsx
  edweiss-app/utils/lectures/remotecontrol/utilsFunctions.tsx
Labels: test

#35 Adds tests for the standard library + Remove configuration files from the SonarCloud code coverage
  .github/workflows/test.yml
  edweiss-app/__test__/config/SyncStorage.test.ts
  edweiss-app/__test__/constants/Sizes.test.ts
  edweiss-app/__test__/constants/Style.test.ts
  edweiss-app/__test__/contexts/__snapshots__/auth.test.tsx.snap
  edweiss-app/__test__/contexts/auth.test.tsx
  edweiss-app/config/SyncStorage.ts
  edweiss-app/constants/Colors.ts
  edweiss-app/constants/Sizes.ts
  edweiss-app/constants/Style.ts
  edweiss-app/constants/Time.ts
  edweiss-app/package.json
Labels: test

#41 Enhance the login and loading pages for the EdWeiss App
  edweiss-app/__test__/app/login/index.test.tsx
  edweiss-app/app/(app)/_layout.tsx
  edweiss-app/app/login/index.tsx
  edweiss-app/assets/images/flower_logo.png
  edweiss-app/assets/images/mountain_logo.png
  edweiss-app/config/i18config.ts
  edweiss-app/locales/en/login.json
Labels: enhancement

#44 Adds our own Cloud Functions sanitization library + Sanitizes all CFs
  edweiss-firebase/functions/package-lock.json
  edweiss-firebase/functions/package.json
  edweiss-firebase/functions/src/functions/action/createQuiz.ts
  edweiss-firebase/functions/src/functions/action/createQuizAttempt.ts
  edweiss-firebase/functions/src/functions/action/updateQuiz.ts
  edweiss-firebase/functions/src/functions/auth/createAccount.ts
  edweiss-firebase/functions/src/functions/experiments/promptAI.ts
  edweiss-firebase/functions/src/functions/fcm/registerFCMToken.ts
  edweiss-firebase/functions/src/functions/fcm/sendFCMPage.ts
  edweiss-firebase/functions/src/functions/lectures/addAudioTranscript.ts
  edweiss-firebase/functions/src/functions/memento/createCard.ts
  edweiss-firebase/functions/src/functions/memento/createDeck.ts
  edweiss-firebase/functions/src/functions/memento/deleteCard.ts
  edweiss-firebase/functions/src/functions/memento/deleteDeck.ts
  edweiss-firebase/functions/src/functions/memento/updateCard.ts
  edweiss-firebase/functions/src/functions/memento/updateDeck.ts
  edweiss-firebase/functions/src/functions/notifs/deleteNotif.ts
  edweiss-firebase/functions/src/functions/notifs/markAsRead.ts
  edweiss-firebase/functions/src/functions/notifs/markAsUnread.ts
  edweiss-firebase/functions/src/functions/notifs/pushNotif.ts
  edweiss-firebase/functions/src/functions/todolist/createTodo.ts
  edweiss-firebase/functions/src/functions/todolist/deleteTodo.ts
  edweiss-firebase/functions/src/functions/todolist/updateTodo.ts
  edweiss-firebase/functions/src/utils/custom-sanitizer/memento.ts
  edweiss-firebase/functions/src/utils/custom-sanitizer/quiz.ts
  edweiss-firebase/functions/src/utils/firebase.ts
  edweiss-firebase/functions/src/utils/sanitizer.ts
  edweiss-firebase/functions/src/utils/status.ts
  edweiss-firebase/functions/tsconfig.json
  package-lock.json
Labels: enhancement

#28 Enhance/memento: multiple cards, decks deletion run without bug
  edweiss-app/__test__/memento/card.test.tsx
  edweiss-app/__test__/memento/deck.test.tsx
  edweiss-app/__test__/memento/editCard.test.tsx
  edweiss-app/app/(app)/deck/[id]/card/creation/index.tsx
  edweiss-app/app/(app)/deck/[id]/card/edition/index.tsx
  edweiss-app/app/(app)/deck/[id]/index.tsx
  edweiss-app/app/(app)/deck/[id]/playingCards.tsx
  edweiss-app/app/(app)/deck/index.tsx
  edweiss-app/components/memento/CardScreenComponent.tsx
  edweiss-app/model/memento.ts
  edweiss-firebase/functions/src/functions/memento/deleteCards.ts
  edweiss-firebase/functions/src/functions/memento/deleteDeck.ts
  edweiss-firebase/functions/src/functions/memento/deleteDecks.ts
  edweiss-firebase/functions/src/model/memento.ts
  edweiss-web/src/model/memento.ts
  model/src/memento.ts
Labels: enhancement

#48 test(quiz): adding tests for QuizComponents and TemporaryQuizStudentView
  edweiss-app/__test__/quiz/CheckMCQPropositionCorrect.test.tsx
  edweiss-app/__test__/quiz/CheckResultColor.test.tsx
  edweiss-app/__test__/quiz/CheckTFCorrect.test.tsx
  edweiss-app/__test__/quiz/MCQDisplay.test.tsx
  edweiss-app/__test__/quiz/QuizDisplay___test___.tsx
  edweiss-app/__test__/quiz/SendWith.test.tsx
  edweiss-app/__test__/quiz/TFDisplay.test.tsx
  edweiss-app/__test__/quiz/TFResultDisplay.test.tsx
  edweiss-app/__test__/quiz/TemporaryQuizStudentView.test.tsx
  edweiss-app/app/(app)/quiz/temporaryQuizStudentView.tsx
  edweiss-app/components/quiz/QuizComponents.tsx
Labels: test

#51 Prevent Button Spamming to Avoid Code Crash in Memento update learning status
  edweiss-app/__test__/memento/card.test.tsx
  edweiss-app/app/(app)/deck/[id]/playingCards.tsx
  edweiss-app/components/memento/CardScreenComponent.tsx
Labels: enhancement

#56 test(quiz): add tests for prof view, delete some files
  edweiss-app/__test__/quiz/DisplayMCQProportions.test.tsx
  edweiss-app/__test__/quiz/DisplayTFProportions.test.tsx
  edweiss-app/__test__/quiz/GetMCQDistribution.test.tsx
  edweiss-app/__test__/quiz/GetTFDistribution.test.tsx
  edweiss-app/__test__/quiz/SingleDistributionDisplay.test.tsx
  edweiss-app/__test__/quiz/TemporaryQuizProfView.test.tsx
  edweiss-app/app/(app)/quiz/quizzesList.tsx
  edweiss-app/app/(app)/quiz/results.tsx
  edweiss-app/app/(app)/quiz/temporaryQuizProfView.tsx
Labels: test

#60 The `Repository` - New way of handling collections and Cloud synchronization with optimistic updates.
  .vscode/settings.json
  edweiss-app/__test__/__mocks__/common.d.ts
  edweiss-app/__test__/__mocks__/core.tsx
  edweiss-app/__test__/__mocks__/index.tsx
  edweiss-app/__test__/__mocks__/repository.tsx
  edweiss-app/__test__/memento/card.test.tsx
  edweiss-app/__test__/memento/deck.test.tsx
  edweiss-app/__test__/memento/editCard.test.tsx
  edweiss-app/app/(app)/(tabs)/community.tsx
  edweiss-app/app/(app)/(tabs)/index.tsx
  edweiss-app/app/(app)/_layout.tsx
  edweiss-app/app/(app)/deck/[id]/card/creation/index.tsx
  edweiss-app/app/(app)/deck/[id]/card/edition/index.tsx
  edweiss-app/app/(app)/deck/[id]/index.tsx
  edweiss-app/app/(app)/deck/[id]/playingCards.tsx
  edweiss-app/app/(app)/deck/_layout.tsx
  edweiss-app/app/(app)/deck/index.tsx
  edweiss-app/components/core/modal/ModalContainer.tsx
  edweiss-app/config/SyncStorage.ts
  edweiss-app/hooks/firebase/firestore.ts
  edweiss-app/hooks/repository.tsx
  edweiss-app/hooks/routeParameters.ts
  edweiss-app/utils/uid.ts
Labels: enhancement

#59 Refractor: bring modifications suggested in PR #38 & and other small modifs
  edweiss-app/__test__/app/(app)/courses/[id]/archive.test.tsx
  edweiss-app/__test__/app/(app)/courses/[id]/index.test.tsx
  edweiss-app/__test__/app/(app)/courses/index.test.tsx
  edweiss-app/__test__/courses/ArchivePage.test.tsx
  edweiss-app/__test__/notifs/notifications.test.tsx
  edweiss-app/app/(app)/(tabs)/_layout.tsx
  edweiss-app/app/(app)/courses/[id]/archive.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/app/(app)/notifs/notifications.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/components/notifs/NotifDisplay.tsx
  edweiss-app/constants/Colors.ts
  edweiss-app/hooks/routeParameters.ts
  edweiss-app/utils/time.ts
Labels: refractoring

#64 Multi language support for the STRC
  edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/abstractRmtCtl.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/modal.test.tsx
  edweiss-app/__test__/utils/lectures/remotecontrol/utilsFunctions.test.ts
  edweiss-app/app/(app)/(tabs)/community.tsx
  edweiss-app/app/(app)/lectures/remotecontrol/index.tsx
  edweiss-app/components/lectures/remotecontrol/abstractRmtCtl.tsx
  edweiss-app/components/lectures/remotecontrol/modal.tsx
  edweiss-app/locales/en/showtime.json
  edweiss-app/model/lectures/lectureDoc.ts
  edweiss-app/utils/lectures/remotecontrol/utilsFunctions.tsx
  edweiss-firebase/functions/.gitignore
  edweiss-firebase/functions/src/functions/lectures/addAudioTranscript.ts
  edweiss-firebase/functions/src/model/lectures/lectureDoc.ts
  edweiss-web/src/model/lectures/lectureDoc.ts
  edweiss-web/src/model/notifs.ts
  model/src/lectures/lectureDoc.ts
Labels: enhancement

#73 Product Owner Report Sprint 6
  README.md
Labels: documentation

#66 `RichText` - A drop-in replacement for `TText` allowing you to render Markdown and LaTeX
  edweiss-app/__test__/components/core/rich-text/RichText.test.ts
  edweiss-app/__test__/components/core/rich-text/__snapshots__/RichText.test.ts.snap
  edweiss-app/app/(app)/(tabs)/community.tsx
  edweiss-app/app/(app)/(tabs)/index.tsx
  edweiss-app/components/core/rich-text/RichText.tsx
  edweiss-app/components/core/rich-text/WebViewMathJaxWrapper.tsx
  edweiss-app/constants/RichTextSpecifications.ts
  edweiss-app/declarations.d.ts
  edweiss-app/hooks/promise.ts
  edweiss-app/package-lock.json
  edweiss-app/package.json
Labels: enhancement
