Repository SnowWhiteEPFL/edweiss, pull requests merged in 2024-12, with the labels that each got.

#61 Add Materials in Course Page, add link between Course Page and Quiz Feature & Add new firebase functions
  .gitignore
  edweiss-app/__test__/app/(app)/courses/[id]/archive.test.tsx
  edweiss-app/__test__/app/(app)/courses/[id]/index.test.tsx
  edweiss-app/__test__/components/courses/AssignmentDisplay.test.tsx
  edweiss-app/app/(app)/courses/[id]/archive.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/components/core/Day.tsx
  edweiss-app/components/core/TText.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/components/courses/MaterialDisplay.tsx
  edweiss-app/locales/en/course.json
  edweiss-app/model/school/courses.ts
  edweiss-app/utils/courses/materialDisplay.tsx
  edweiss-app/utils/time.ts
  edweiss-firebase/functions/src/functions/course/addAssignment.ts
  edweiss-firebase/functions/src/functions/course/addAssistant.ts
  edweiss-firebase/functions/src/functions/course/addMaterial.ts
  edweiss-firebase/functions/src/functions/course/addProfessor.ts
  edweiss-firebase/functions/src/functions/course/createCourse.ts
  edweiss-firebase/functions/src/functions/course/removeAssignment.ts
  edweiss-firebase/functions/src/functions/course/removeAssistant.ts
  edweiss-firebase/functions/src/functions/course/removeMaterial.ts
  edweiss-firebase/functions/src/functions/course/removeProfessor.ts
  edweiss-firebase/functions/src/functions/course/toogleCourse.ts
  edweiss-firebase/functions/src/functions/course/updateAssignment.ts
  edweiss-firebase/functions/src/functions/course/updateCourse.ts
  edweiss-firebase/functions/src/functions/course/updateMaterial.ts
  edweiss-firebase/functions/src/model/school/courses.ts
  edweiss-firebase/functions/src/utils/custom-sanitizer/quiz.ts
  edweiss-firebase/functions/src/utils/sanitizer.ts
  model/src/school/courses.ts
Labels: enhancement

#70 Quiz creation + modal color change + quiz model change
  edweiss-app/__test__/quiz/TemporaryQuizProfView.test.tsx
  edweiss-app/app/(app)/quiz/createQuizPage.tsx
  edweiss-app/app/(app)/quiz/temporaryQuizStudentView.tsx
  edweiss-app/components/core/modal/ModalContainer.tsx
  edweiss-app/config/i18config.ts
  edweiss-app/locales/en/quiz.json
  edweiss-app/model/quizzes.ts
  edweiss-firebase/functions/src/functions/action/createQuiz.ts
  edweiss-firebase/functions/src/model/quizzes.ts
  edweiss-firebase/functions/src/utils/custom-sanitizer/quiz.ts
  edweiss-web/src/model/quizzes.ts
  model/src/quizzes.ts
Labels: enhancement

#74 Integration of Sprint 6 and Sprint 7 Changes with Optimistic Updates and UI Enhancements
  edweiss-app/__test__/memento/card.test.tsx
  edweiss-app/__test__/memento/cardModal.test.tsx
  edweiss-app/__test__/memento/cardScreenComponent.test.tsx
  edweiss-app/__test__/memento/createCard.test.tsx
  edweiss-app/__test__/memento/deck.test.tsx
  edweiss-app/__test__/memento/editCard.test.tsx
  edweiss-app/__test__/memento/layout.test.tsx
  edweiss-app/__test__/memento/utilsFunctions.test.tsx
  edweiss-app/app/(app)/deck/[id]/card/creation/index.tsx
  edweiss-app/app/(app)/deck/[id]/card/edition/index.tsx
  edweiss-app/app/(app)/deck/[id]/index.tsx
  edweiss-app/app/(app)/deck/[id]/playingCards.tsx
  edweiss-app/app/(app)/deck/_layout.tsx
  edweiss-app/app/(app)/deck/index.tsx
  edweiss-app/components/memento/CardListDisplayComponent.tsx
  edweiss-app/components/memento/CardScreenComponent.tsx
  edweiss-app/components/memento/DeleteDeckModalAction.tsx
  edweiss-app/components/memento/ModalDisplay.tsx
  edweiss-app/components/memento/OptionCardModalAction.tsx
  edweiss-app/model/memento.ts
  edweiss-app/utils/memento/utilsFunctions.tsx
  edweiss-firebase/functions/src/model/memento.ts
  edweiss-web/src/model/memento.ts
  model/src/memento.ts
Labels: enhancement

#62 Enhance User Experience by Simplifying Modal, Adding Loading States and Adding Modals to convey clear instruction for users
  edweiss-app/__test__/memento/editCard.test.tsx
  edweiss-app/__test__/memento/utilsFunctions.test.tsx
  edweiss-app/app/(app)/deck/[id]/card/creation/index.tsx
Labels: enhancement

#75 Go To Page from the STRC
  edweiss-app/__test__/app/(app)/lectures/remotecontrol/jumpToSlide.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/abstractRmtCtl.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/modal.test.tsx
  edweiss-app/__test__/utils/lectures/remotecontrol/utilsFunctions.test.ts
  edweiss-app/app/(app)/lectures/remotecontrol/index.tsx
  edweiss-app/app/(app)/lectures/remotecontrol/jumpToSlide.tsx
  edweiss-app/components/input/FancyTextInput.tsx
  edweiss-app/components/lectures/remotecontrol/abstractRmtCtl.tsx
  edweiss-app/components/lectures/remotecontrol/modal.tsx
  edweiss-app/locales/en/showtime.json
  edweiss-app/utils/lectures/remotecontrol/utilsFunctions.tsx
  edweiss-firebase/functions/src/functions/lectures/addAudioTranscript.ts
Labels: enhancement

#71 Add Functionality for Adding Assignments & Materials and Modifying Course Parameters
  edweiss-app/app/(app)/(tabs)/index.tsx
  edweiss-app/app/(app)/courses/[id]/archive.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/components/courses/AddAssignment.tsx
  edweiss-app/components/courses/AddMaterial.tsx
  edweiss-app/components/courses/CourseParameters.tsx
  edweiss-app/components/courses/SelectActionsCourse.tsx
  edweiss-app/components/input/FancyButton.tsx
  edweiss-app/locales/en/course.json
  edweiss-app/package-lock.json
  edweiss-app/package.json
  edweiss-firebase/functions/src/functions/course/updateCredits.ts
  edweiss-firebase/functions/src/functions/course/updateDescription.ts
  edweiss-firebase/functions/src/functions/course/updateName.ts
  edweiss-firebase/functions/src/functions/course/updateSection.ts
Labels: enhancement

#79 Provide StopWatch integration in the STRC
  edweiss-app/__test__/app/(app)/lectures/remotecontrol/jumpToSlide.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/abstractRmtCtl.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/modal.test.tsx
  edweiss-app/components/lectures/remotecontrol/abstractRmtCtl.tsx
  edweiss-app/components/lectures/remotecontrol/modal.tsx
  edweiss-app/locales/en/showtime.json
  edweiss-firebase/functions/package-lock.json
Labels: enhancement

#84 Scrum Master Report Sprint 8
  README.md
Labels: documentation

#83 The Forum - An embedded platform for questions, comments and answers directly in your app
  edweiss-app/app/(app)/courses/[id]/forum/[postId]/index.tsx
  edweiss-app/app/(app)/courses/[id]/forum/create-post.tsx
  edweiss-app/app/(app)/courses/[id]/forum/index.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/app/_layout.tsx
  edweiss-app/assets/fonts/Inter-Bold.ttf
  edweiss-app/assets/fonts/Inter-ExtraLight.ttf
  edweiss-app/assets/fonts/Inter-Light.ttf
  edweiss-app/assets/fonts/Inter-Medium.ttf
  edweiss-app/assets/fonts/Inter-Regular.ttf
  edweiss-app/assets/fonts/Inter-SemiBold.ttf
  edweiss-app/assets/fonts/Inter-Thin.ttf
  edweiss-app/assets/fonts/Inter.ttf
  edweiss-app/components/Avatar.tsx
  edweiss-app/components/core/TText.tsx
  edweiss-app/components/core/header/HeaderButtons.tsx
  edweiss-app/components/core/header/RouteHeader.tsx
  edweiss-app/components/core/rich-text/WebViewMathJaxWrapper.tsx
  edweiss-app/config/i18config.ts
  edweiss-app/hooks/firebase/firestore.ts
  edweiss-app/locales/en/common.json
  edweiss-app/locales/en/forum.json
  edweiss-app/model/forum.ts
  edweiss-app/utils/time.ts
  edweiss-firebase/functions/src/functions/forum/createAnswer.ts
  edweiss-firebase/functions/src/functions/forum/createPost.ts
  edweiss-firebase/functions/src/functions/forum/setLikePost.ts
  edweiss-firebase/functions/src/model/forum.ts
  edweiss-firebase/functions/src/utils/firestore.ts
  edweiss-firebase/functions/src/utils/status.ts
  edweiss-web/src/model/forum.ts
  edweiss-web/src/model/school/courses.ts
  model/src/forum.ts
Labels: enhancement

#82 Feat(memento): integrate rich text feature for flashcards
  edweiss-app/__test__/memento/card.test.tsx
  edweiss-app/__test__/memento/cardModal.test.tsx
  edweiss-app/__test__/memento/cardScreenComponent.test.tsx
  edweiss-app/__test__/memento/createCard.test.tsx
  edweiss-app/__test__/memento/editCard.test.tsx
  edweiss-app/app/(app)/deck/[id]/card/creation/index.tsx
  edweiss-app/app/(app)/deck/[id]/card/edition/index.tsx
  edweiss-app/app/(app)/deck/[id]/card/index.tsx
  edweiss-app/app/(app)/deck/[id]/index.tsx
  edweiss-app/app/(app)/deck/[id]/playingCards.tsx
  edweiss-app/app/(app)/deck/index.tsx
  edweiss-app/components/memento/CardListDisplayComponent.tsx
  edweiss-app/components/memento/CardScreenComponent.tsx
  edweiss-app/components/memento/ModalDisplay.tsx
  edweiss-app/locales/en/memento.json
Labels: enhancement

#87 Forum tests for sufficient coverage >80%
  edweiss-app/__test__/app/(app)/courses/[id]/forum/create-post.test.tsx
  edweiss-app/__test__/app/(app)/courses/[id]/forum/index.test.tsx
  edweiss-app/__test__/app/(app)/courses/[id]/forum/postId.test.tsx
  edweiss-app/__test__/home_page/calendar.test.tsx
  edweiss-app/__test__/home_page/day.test.tsx
  edweiss-app/__test__/home_page/getCurrentDay.test.tsx
  edweiss-app/__test__/home_page/getCurrentTimeInMinutes.test.tsx
  edweiss-app/__test__/home_page/getWeekDays.test.tsx
  edweiss-app/__test__/home_page/my_calendar.test.tsx
  edweiss-app/__test__/home_page/period_block.test.tsx
  edweiss-app/__test__/utils/time.test.ts
  edweiss-app/app/(app)/courses/[id]/forum/[postId]/index.tsx
  edweiss-app/app/(app)/courses/[id]/forum/create-post.tsx
  edweiss-app/app/(app)/courses/[id]/forum/index.tsx
  edweiss-app/locales/en/forum.json
  edweiss-app/utils/time.ts
Labels: test

#89 Live Lecturer Transcript Translation
  edweiss-app/__test__/components/lectures/slides/modal.test.tsx
  edweiss-app/__test__/showtime/LectureScreen.test.tsx
  edweiss-app/__test__/utils/lectures/slides/utilsFunctions.test.ts
  edweiss-app/app/(app)/lectures/slides/index.tsx
  edweiss-app/components/lectures/remotecontrol/modal.tsx
  edweiss-app/components/lectures/slides/modal.tsx
  edweiss-app/locales/en/showtime.json
  edweiss-app/model/lectures/lectureDoc.ts
  edweiss-app/package-lock.json
  edweiss-app/utils/lectures/slides/utilsFunctions.tsx
  edweiss-firebase/functions/src/functions/course/updateCredits.ts
  edweiss-firebase/functions/src/functions/course/updateDescription.ts
  edweiss-firebase/functions/src/functions/course/updateName.ts
  edweiss-firebase/functions/src/functions/course/updateSection.ts
  edweiss-firebase/functions/src/functions/lectures/addAudioTranscript.ts
  edweiss-firebase/functions/src/functions/lectures/likeQuestion.ts
  edweiss-firebase/functions/src/model/lectures/lectureDoc.ts
  edweiss-web/src/model/lectures/lectureDoc.ts
  edweiss-web/src/model/school/courses.ts
  model/src/lectures/lectureDoc.ts
Labels: enhancement

#86 Lecture quiz creation and view, quiz UI revamp
  edweiss-app/__test__/quiz/DisplayMCQProportions.test.tsx
  edweiss-app/__test__/quiz/DisplayTFProportions.test.tsx
  edweiss-app/__test__/quiz/QuizStudentView.test.tsx
  edweiss-app/__test__/quiz/SendWith.test.tsx
  edweiss-app/__test__/quiz/SingleDistributionDisplay.test.tsx
  edweiss-app/app/(app)/quiz/createLectureQuizPage.tsx
  edweiss-app/app/(app)/quiz/createQuizPage.tsx
  edweiss-app/app/(app)/quiz/lectureQuizStudentView.tsx
  edweiss-app/app/(app)/quiz/quizStudentView.tsx
  edweiss-app/app/(app)/quiz/temporaryQuizProfView.tsx
  edweiss-app/components/input/CoolCheckBox.tsx
  edweiss-app/components/input/RadioSelectables.tsx
  edweiss-app/components/quiz/QuizComponents.tsx
  edweiss-app/locales/en/quiz.json
  edweiss-app/model/lectures/lectureDoc.ts
  edweiss-app/model/quizzes.ts
  edweiss-firebase/functions/src/functions/action/createLectureQuiz.ts
  edweiss-firebase/functions/src/functions/action/createLectureQuizAttempt.ts
  edweiss-firebase/functions/src/functions/action/createQuiz.ts
  edweiss-firebase/functions/src/functions/action/createQuizAttempt.ts
  edweiss-firebase/functions/src/functions/action/updateQuiz.ts
  edweiss-firebase/functions/src/model/lectures/lectureDoc.ts
  edweiss-firebase/functions/src/model/quizzes.ts
  edweiss-firebase/functions/src/utils/custom-sanitizer/quiz.ts
  edweiss-web/src/model/lectures/lectureDoc.ts
  edweiss-web/src/model/quizzes.ts
  model/src/lectures/lectureDoc.ts
  model/src/quizzes.ts
Labels: enhancement

#91 Live Question integration in STRC and broadcast to ST!
  edweiss-app/__test__/app/(app)/lectures/remotecontrol/questionToSlide.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/abstractRmtCtl.test.tsx
  edweiss-app/__test__/components/lectures/remotecontrol/modal.test.tsx
  edweiss-app/__test__/showtime/LectureScreen.test.tsx
  edweiss-app/app/(app)/lectures/remotecontrol/questionToSlide.tsx
  edweiss-app/app/(app)/lectures/slides/index.tsx
  edweiss-app/app/(app)/quiz/createLectureQuizPage.tsx
  edweiss-app/app/(app)/quiz/lectureQuizStudentView.tsx
  edweiss-app/app/(app)/quiz/temporaryQuizProfView.tsx
  edweiss-app/components/lectures/remotecontrol/abstractRmtCtl.tsx
  edweiss-app/components/lectures/remotecontrol/modal.tsx
  edweiss-app/locales/en/showtime.json
  edweiss-app/model/lectures/lectureDoc.ts
  edweiss-firebase/functions/src/functions/action/createLectureQuiz.ts
  edweiss-firebase/functions/src/functions/lectures/broadcastQuestion.ts
  edweiss-firebase/functions/src/functions/lectures/clearQuestionEvent.ts
  edweiss-firebase/functions/src/functions/lectures/createQuestion.ts
  edweiss-firebase/functions/src/functions/lectures/markQuestionAsAnswered.ts
  edweiss-firebase/functions/src/model/lectures/lectureDoc.ts
  edweiss-firebase/functions/src/utils/custom-sanitizer/quiz.ts
  edweiss-web/src/model/lectures/lectureDoc.ts
  model/src/lectures/lectureDoc.ts
Labels: enhancement

#95 Feature: Lecture quiz component that can be displayed in a slide
  edweiss-app/app/(app)/(tabs)/community.tsx
  edweiss-app/app/(app)/quiz/createQuizPage.tsx
  edweiss-app/app/(app)/quiz/lectureQuizStudentView.tsx
  edweiss-app/app/(app)/quiz/temporaryQuizProfView.tsx
  edweiss-app/components/core/rich-text/WebViewMathJaxWrapper.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/components/quiz/LectureQuizComponents.tsx
  edweiss-app/components/quiz/QuizComponents.tsx
  edweiss-app/locales/en/quiz.json
  edweiss-app/model/quizzes.ts
  edweiss-firebase/functions/src/functions/action/toggleLectureQuizResult.ts
  edweiss-firebase/functions/src/model/quizzes.ts
  edweiss-web/src/model/quizzes.ts
  model/src/quizzes.ts
Labels: enhancement

#101 AI Generated Quizzes from Material URL
  edweiss-app/app/(app)/(tabs)/community.tsx
  edweiss-app/model/lectures/lectureDoc.ts
  edweiss-app/model/quizzes.ts
  edweiss-firebase/functions/package-lock.json
  edweiss-firebase/functions/package.json
  edweiss-firebase/functions/src/functions/action/generateQuizContentFromMaterial.ts
  edweiss-firebase/functions/src/functions/action/toggleLectureQuizResult.ts
  edweiss-firebase/functions/src/model/lectures/lectureDoc.ts
  edweiss-firebase/functions/src/model/quizzes.ts
  edweiss-web/src/model/lectures/lectureDoc.ts
  edweiss-web/src/model/quizzes.ts
  model/src/lectures/lectureDoc.ts
  model/src/quizzes.ts
Labels: enhancement

#107 Feature/good login page
  edweiss-app/__test__/app/login/index.test.tsx
  edweiss-app/android/app/build.gradle
  edweiss-app/android/app/src/main/AndroidManifest.xml
  edweiss-app/android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  edweiss-app/android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  edweiss-app/android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  edweiss-app/android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  edweiss-app/android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  edweiss-app/android/app/src/main/res/values/colors.xml
  edweiss-app/android/app/src/main/res/values/strings.xml
  edweiss-app/android/app/src/main/res/values/styles.xml
  edweiss-app/app.config.js
  edweiss-app/app/(app)/(tabs)/index.tsx
  edweiss-app/app/(app)/_layout.tsx
  edweiss-app/app/login/fake_terms_of_use.tsx
  edweiss-app/app/login/index.tsx
  edweiss-app/assets/images/edweiss.svg
  edweiss-app/assets/images/edweiss2.svg
  edweiss-app/assets/images/icon.png
  edweiss-app/assets/images/splash.png
  edweiss-app/components/InitialLoadingScreen.tsx
  edweiss-app/components/animations/HelloWave.tsx
  edweiss-app/components/core/containers/TSafeArea.tsx
  edweiss-app/components/courses/AssignmentDisplay.tsx
  edweiss-app/locales/en/login.json
Labels: enhancement

#105 Upload documents in Materials
  edweiss-app/__test__/app/(app)/courses/[id]/archive.test.tsx
  edweiss-app/__test__/app/(app)/courses/[id]/index.test.tsx
  edweiss-app/__test__/components/core/SVGImage.test.tsx
  edweiss-app/__test__/components/courses/AssignmentDisplay.test.tsx
  edweiss-app/__test__/components/courses/MaterialComponent.test.tsx
  edweiss-app/__test__/utils/courses/coursesActionsFunctions.test.tsx
  edweiss-app/__test__/utils/notifs/notifsActionFunctions.test.tsx
  edweiss-app/app/(app)/(tabs)/community.tsx
  edweiss-app/app/(app)/calendar/horizontalCalendar.tsx
  edweiss-app/app/(app)/courses/[id]/archive.tsx
  edweiss-app/app/(app)/courses/[id]/index.tsx
  edweiss-app/app/(app)/courses/[id]/materials/[materialId]/index.tsx
  edweiss-app/app/(app)/lectures/slides/index.tsx
  edweiss-app/app/(app)/notifs/notifications.tsx
  edweiss-app/components/core/SVGImage.tsx
  edweiss-app/components/courses/AssignmentComponent.tsx
  edweiss-app/components/courses/DocumentDisplay.tsx
  edweiss-app/components/courses/MaterialComponent.tsx
  edweiss-app/components/courses/MaterialDisplay.tsx
  edweiss-app/config/firebase.ts
  edweiss-app/locales/en/course.json
  edweiss-app/locales/en/notifications.json
  edweiss-app/model/notifs.ts
  edweiss-app/model/school/courses.ts
  edweiss-app/utils/courses/coursesActionsFunctions.tsx
  edweiss-app/utils/notifs/notifsActionsFunctions.tsx
  edweiss-firebase/functions/src/functions/action/toggleLectureQuizResult.ts
  edweiss-firebase/functions/src/functions/course/addMaterial.ts
  edweiss-firebase/functions/src/functions/course/updateMaterial.ts
  edweiss-firebase/functions/src/functions/lectures/createQuestion.ts
  edweiss-firebase/functions/src/functions/notifs/pushNotif.ts
  edweiss-firebase/functions/src/model/notifs.ts
  edweiss-firebase/functions/src/model/school/courses.ts
  edweiss-firebase/package-lock.json
  model/src/notifs.ts
  model/src/school/courses.ts
Labels: enhancement

#109 Integrate AI-Powered Flashcard Creation into Course Materials, Add Search Bar and Update Sharing UI
  edweiss-app/__test__/memento/components/new_smthWrongComponent.test.tsx
  edweiss-app/__test__/memento/new_aiGenerateDeck.test.tsx
  edweiss-app/__test__/memento/new_deck.test.tsx
  edweiss-app/__test__/memento/new_shareDeckCardScreen.test.tsx
  edweiss-app/app/(app)/courses/[id]/deck/[deckId]/index.tsx
  edweiss-app/app/(app)/courses/[id]/deck/[deckId]/playingCards.tsx
  edweiss-app/app/(app)/courses/[id]/deck/[deckId]/shareDeckCard.tsx
  edweiss-app/app/(app)/courses/[id]/deck/aiGenerateDeck.tsx
  edweiss-app/app/(app)/courses/[id]/deck/index.tsx
  edweiss-app/components/courses/MaterialDisplay.tsx
  edweiss-app/components/memento/CardDisplayComponent.tsx
  edweiss-app/components/memento/SmthWrongComponent.tsx
  edweiss-app/model/memento.ts
  edweiss-firebase/functions/package-lock.json
  edweiss-firebase/functions/package.json
  edweiss-firebase/functions/src/functions/memento/createDeckFromMaterial.ts
  edweiss-firebase/functions/src/index.ts
  edweiss-firebase/functions/src/model/memento.ts
  edweiss-web/src/model/memento.ts
  model/src/memento.ts
Labels: enhancement

#112 Check the type of document before calling AI deck generation on a document
  edweiss-app/__test__/memento/new_aiGenerateDeck.test.tsx
  edweiss-app/app/(app)/courses/[id]/deck/aiGenerateDeck.tsx
  edweiss-app/components/courses/MaterialDisplay.tsx
Labels: enhancement

#113 feature: give possibility to switch permissions for grading
  edweiss-app/app/(app)/(tabs)/profile.tsx
  edweiss-app/model/users.ts
  edweiss-app/utils/auth/authActionsFunctions.tsx
  edweiss-firebase/functions/src/functions/auth/switchPermissions.ts
  edweiss-firebase/functions/src/model/users.ts
  model/src/users.ts
Labels: enhancement

#117 refactor: enhance user filtering and improve component documentation
  edweiss-app/app/(app)/courses/[id]/deck/[deckId]/index.tsx
  edweiss-app/app/(app)/courses/[id]/deck/[deckId]/playingCards.tsx
  edweiss-app/app/(app)/courses/[id]/deck/[deckId]/shareDeckCard.tsx
  edweiss-app/app/(app)/courses/[id]/deck/aiGenerateDeck.tsx
  edweiss-app/components/memento/CardDisplayComponent.tsx
  edweiss-app/components/memento/CardListDisplayComponent.tsx
  edweiss-app/components/memento/CreateDeleteEditCardModal.tsx
  edweiss-app/components/memento/ModalDisplay.tsx
  edweiss-app/components/memento/SmthWrongComponent.tsx
Labels: documentation

#118 Final/memento doc
  edweiss-app/app/(app)/courses/[id]/deck/aiGenerateDeck.tsx
  edweiss-app/app/(app)/courses/[id]/deck/index.tsx
  edweiss-app/components/memento/CardDisplayComponent.tsx
Labels: documentation
